name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m venv .venv
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/pip install black isort mypy
          if [ -f requirements.txt ]; then .venv/bin/pip install -r requirements.txt; fi
      - name: Lint
        run: |
          make check
      - name: Test
        run: |
          make test
